# Generated by Django 5.1.15 on 2026-03-18 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('methodology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='ACModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('series', models.CharField(blank=True, default='', max_length=255, verbose_name='Серия')),
                ('inner_unit', models.CharField(max_length=255, verbose_name='Модель внутреннего блока')),
                ('outer_unit', models.CharField(blank=True, default='', max_length=255, verbose_name='Модель наружного блока')),
                ('nominal_capacity', models.FloatField(blank=True, null=True, verbose_name='Номинальная холодопроизводительность (кВт)')),
                ('publish_status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('published', 'Опубликован'), ('archived', 'В архиве')], db_index=True, default='draft', max_length=20, verbose_name='Статус публикации')),
                ('total_index', models.FloatField(db_index=True, default=0, verbose_name='Итоговый индекс')),
                ('youtube_url', models.URLField(blank=True, default='', max_length=512)),
                ('rutube_url', models.URLField(blank=True, default='', max_length=512)),
                ('vk_url', models.URLField(blank=True, default='', max_length=512)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='brands.brand', verbose_name='Бренд')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='catalog.equipmenttype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Модель кондиционера',
                'verbose_name_plural': 'Модели кондиционеров',
                'ordering': ['-total_index'],
            },
        ),
        migrations.CreateModel(
            name='ModelRawValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('raw_value', models.CharField(blank=True, default='', max_length=500, verbose_name='Значение')),
                ('numeric_value', models.FloatField(blank=True, null=True, verbose_name='Числовое значение')),
                ('source', models.CharField(blank=True, default='', max_length=255, verbose_name='Источник')),
                ('source_url', models.URLField(blank=True, default='', max_length=512, verbose_name='Ссылка на источник')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('verification_status', models.CharField(choices=[('catalog', 'Данные по каталогу'), ('editorial', 'Проверено редакцией'), ('lab', 'Подтверждено лабораторией')], default='catalog', max_length=20, verbose_name='Статус верификации')),
                ('lab_status', models.CharField(choices=[('not_measured', 'Не измерено'), ('pending', 'Ожидает измерения'), ('not_in_mode', 'Не участвует в данном режиме'), ('measured', 'Измерено')], default='not_measured', max_length=20, verbose_name='Статус лаб. измерения')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_values', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил данные')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='methodology.criterion', verbose_name='Критерий')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_values', to=settings.AUTH_USER_MODEL, verbose_name='Внёс данные')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_values', to='catalog.acmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Значение параметра модели',
                'verbose_name_plural': 'Значения параметров моделей',
                'ordering': ['criterion__display_order'],
                'constraints': [models.UniqueConstraint(fields=('model', 'criterion'), name='unique_model_criterion_value')],
            },
        ),
        migrations.CreateModel(
            name='ModelRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(choices=[('ru', 'Россия'), ('eu', 'Европа')], max_length=10, verbose_name='Регион')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='catalog.acmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Доступность в регионе',
                'verbose_name_plural': 'Доступность в регионах',
                'constraints': [models.UniqueConstraint(fields=('model', 'region_code'), name='unique_model_region')],
            },
        ),
    ]
