# Generated by Django 5.1.15 on 2026-03-30 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_convert_capacity_and_compressor_to_watts'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmodel',
            name='cons_text',
            field=models.TextField(blank=True, default='', verbose_name='Минусы (AI)'),
        ),
        migrations.AddField(
            model_name='acmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Рекомендованная цена (руб.)'),
        ),
        migrations.AddField(
            model_name='acmodel',
            name='pros_text',
            field=models.TextField(blank=True, default='', verbose_name='Плюсы (AI)'),
        ),
        migrations.AlterField(
            model_name='acmodel',
            name='nominal_capacity',
            field=models.FloatField(blank=True, null=True, verbose_name='Номинальная холодопроизводительность (Вт)'),
        ),
        migrations.CreateModel(
            name='ACModelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to='ac_photos/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.acmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Фото модели',
                'verbose_name_plural': 'Фото моделей',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ACModelSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название поставщика')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='catalog.acmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Поставщик (Где купить)',
                'verbose_name_plural': 'Поставщики (Где купить)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
