# Generated by Django 5.1.15 on 2026-04-13 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_acmodel_cons_text_acmodel_price_acmodel_pros_text_and_more'),
        ('methodology', '0021_alter_criterion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='modelrawvalue',
            name='unique_model_criterion_value',
        ),
        migrations.AddField(
            model_name='modelrawvalue',
            name='criterion_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Дублирует criterion.code для сохранения идентичности при удалении критерия', max_length=50, verbose_name='Код критерия'),
        ),
        migrations.AlterField(
            model_name='modelrawvalue',
            name='criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values', to='methodology.criterion', verbose_name='Критерий'),
        ),
        migrations.AddConstraint(
            model_name='modelrawvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('criterion__isnull', False)), fields=('model', 'criterion'), name='unique_model_criterion_value'),
        ),
        migrations.AddConstraint(
            model_name='modelrawvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('criterion__isnull', True)), fields=('model', 'criterion_code'), name='unique_model_criterion_code_orphan'),
        ),
    ]
