# Generated by Django 5.1.15 on 2026-04-13 15:22

from django.db import migrations


def backfill_criterion_code(apps, schema_editor):
    ModelRawValue = apps.get_model("catalog", "ModelRawValue")
    qs = ModelRawValue.objects.filter(criterion__isnull=False, criterion_code="").select_related("criterion")
    batch = []
    for rv in qs.iterator(chunk_size=500):
        rv.criterion_code = rv.criterion.code
        batch.append(rv)
        if len(batch) >= 500:
            ModelRawValue.objects.bulk_update(batch, ["criterion_code"])
            batch = []
    if batch:
        ModelRawValue.objects.bulk_update(batch, ["criterion_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_modelrawvalue_unique_model_criterion_value_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_criterion_code, migrations.RunPython.noop),
    ]
