# Generated by Django 5.1.15 on 2026-04-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_backfill_criterion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', help_text='Генерируется автоматически из бренда, серии и блоков', max_length=500, verbose_name='URL-slug'),
        ),
    ]
