# Generated by Django 5.1.15 on 2026-04-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_add_slug_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrawvalue',
            name='lab_status',
            field=models.CharField(choices=[('not_measured', 'Не измерено'), ('pending', 'Ожидает измерения'), ('not_in_mode', 'Не участвует в данном режиме'), ('measured', 'Измерено')], db_index=True, default='not_measured', max_length=20, verbose_name='Статус лаб. измерения'),
        ),
        migrations.AlterField(
            model_name='modelrawvalue',
            name='verification_status',
            field=models.CharField(choices=[('catalog', 'Данные по каталогу'), ('editorial', 'Проверено редакцией'), ('lab', 'Подтверждено лабораторией')], db_index=True, default='catalog', max_length=20, verbose_name='Статус верификации'),
        ),
    ]
