# Generated by Django 5.1.15 on 2026-04-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_add_index_verification_lab_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelrawvalue',
            options={'ordering': ['criterion__code'], 'verbose_name': 'Значение параметра модели', 'verbose_name_plural': 'Значения параметров моделей'},
        ),
    ]
