# Generated by Django 5.1.15 on 2026-04-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_rename_da_to_est_binary_raw_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmodelphoto',
            name='alt',
            field=models.CharField(blank=True, default='', help_text='Alt-текст для SEO и доступности', max_length=255, verbose_name='Alt-текст'),
        ),
    ]
