# Generated by Django 5.1.15 on 2026-04-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0006_expand_origin_type_free_text'),
        ('catalog', '0013_acmodelphoto_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('custom_brand_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Бренд (если нет в списке)')),
                ('series', models.CharField(blank=True, default='', max_length=255, verbose_name='Серия')),
                ('inner_unit', models.CharField(max_length=255, verbose_name='Модель внутреннего блока')),
                ('outer_unit', models.CharField(max_length=255, verbose_name='Модель наружного блока')),
                ('compressor_model', models.CharField(max_length=255, verbose_name='Модель компрессора')),
                ('nominal_capacity_btu', models.PositiveIntegerField(verbose_name='Номинальная холодопроизводительность (BTU)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (руб.)')),
                ('drain_pan_heater', models.BooleanField(verbose_name='Обогрев поддона')),
                ('erv', models.BooleanField(verbose_name='Наличие ЭРВ')),
                ('fan_speed_outdoor', models.BooleanField(verbose_name='Регулировка оборотов вент. наруж. блока')),
                ('remote_backlight', models.BooleanField(verbose_name='Подсветка экрана пульта')),
                ('fan_speeds_indoor', models.PositiveSmallIntegerField(verbose_name='Кол-во скоростей вент. внутр. блока')),
                ('fine_filters', models.PositiveSmallIntegerField(verbose_name='Кол-во фильтров тонкой очистки')),
                ('ionizer_type', models.CharField(max_length=100, verbose_name='Тип ионизатора')),
                ('russian_remote', models.CharField(max_length=100, verbose_name='Русифицированный пульт ДУ')),
                ('uv_lamp', models.CharField(max_length=100, verbose_name='УФ-лампа')),
                ('inner_he_length_mm', models.FloatField(verbose_name='Длина теплообменника внутр. блока (мм)')),
                ('inner_he_tube_count', models.PositiveIntegerField(verbose_name='Кол-во трубок теплообменника внутр. блока')),
                ('inner_he_tube_diameter_mm', models.FloatField(verbose_name='Диаметр трубок теплообменника внутр. блока (мм)')),
                ('inner_he_surface_area', models.FloatField(default=0, editable=False, verbose_name='Площадь труб теплообменника внутр. блока (м²)')),
                ('outer_he_length_mm', models.FloatField(verbose_name='Длина теплообменника наруж. блока (мм)')),
                ('outer_he_tube_count', models.PositiveIntegerField(verbose_name='Кол-во трубок теплообменника наруж. блока')),
                ('outer_he_tube_diameter_mm', models.FloatField(verbose_name='Диаметр трубок теплообменника наруж. блока (мм)')),
                ('outer_he_thickness_mm', models.FloatField(verbose_name='Толщина теплообменника наруж. блока (мм)')),
                ('outer_he_surface_area', models.FloatField(default=0, editable=False, verbose_name='Площадь труб теплообменника наруж. блока (м²)')),
                ('video_url', models.URLField(blank=True, default='', max_length=512, verbose_name='Ссылка на видео измерений')),
                ('buy_url', models.URLField(blank=True, default='', max_length=512, verbose_name='Где купить (ссылка)')),
                ('supplier_url', models.URLField(blank=True, default='', max_length=512, verbose_name='Сайт поставщика')),
                ('submitter_email', models.EmailField(max_length=254, verbose_name='E-mail отправителя')),
                ('consent', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Заметки администратора')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='brands.brand', verbose_name='Бренд')),
                ('converted_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submission', to='catalog.acmodel', verbose_name='Созданная модель')),
            ],
            options={
                'verbose_name': 'Заявка на добавление кондиционера',
                'verbose_name_plural': 'Заявки на добавление кондиционеров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to='submissions/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='submissions.acsubmission', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Фото заявки',
                'verbose_name_plural': 'Фото заявок',
                'ordering': ['order', 'id'],
            },
        ),
    ]
