# Generated by Django 5.1.15 on 2026-03-18 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(verbose_name='Позиция в рейтинге')),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд / Название')),
                ('model_name', models.CharField(max_length=512, verbose_name='Модель')),
                ('youtube_url', models.URLField(blank=True, default='', max_length=512)),
                ('rutube_url', models.URLField(blank=True, default='', max_length=512)),
                ('vk_url', models.URLField(blank=True, default='', max_length=512)),
                ('total_score', models.FloatField(default=0, verbose_name='Итоговый балл')),
            ],
            options={
                'verbose_name': 'Кондиционер',
                'verbose_name_plural': 'Кондиционеры',
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255, verbose_name='Параметр')),
                ('raw_value', models.CharField(max_length=255, verbose_name='Значение')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='Ед. измерения')),
                ('score', models.FloatField(default=0, verbose_name='Баллы (индекс)')),
                ('air_conditioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='ratings.airconditioner')),
            ],
            options={
                'verbose_name': 'Значение параметра',
                'verbose_name_plural': 'Значения параметров',
                'ordering': ['id'],
                'unique_together': {('air_conditioner', 'parameter_name')},
            },
        ),
    ]
