# Generated by Django 5.1.15 on 2026-03-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parametervalue',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='airconditioner',
            name='total_score',
            field=models.FloatField(db_index=True, default=0, verbose_name='Итоговый балл'),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='parameter_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Параметр'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.UniqueConstraint(fields=('air_conditioner', 'parameter_name'), name='unique_ac_parameter'),
        ),
    ]
