# Generated by Django 5.1.15 on 2026-03-18 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('methodology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('running', 'Выполняется'), ('completed', 'Завершён'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('models_processed', models.PositiveIntegerField(default=0, verbose_name='Обработано моделей')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('methodology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='methodology.methodologyversion', verbose_name='Методика')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Запустил')),
            ],
            options={
                'verbose_name': 'Запуск расчёта',
                'verbose_name_plural': 'Запуски расчётов',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(blank=True, default='', max_length=500, verbose_name='Исходное значение')),
                ('normalized_score', models.FloatField(default=0, verbose_name='Нормированный балл (0-100)')),
                ('weighted_score', models.FloatField(default=0, verbose_name='Взвешенный балл')),
                ('above_reference', models.BooleanField(default=False, help_text='Значение превышает max (эталонное значение)', verbose_name='Выше эталона')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_results', to='methodology.criterion', verbose_name='Критерий')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_results', to='catalog.acmodel', verbose_name='Модель')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scoring.calculationrun', verbose_name='Запуск расчёта')),
            ],
            options={
                'verbose_name': 'Результат расчёта',
                'verbose_name_plural': 'Результаты расчётов',
                'ordering': ['criterion__display_order'],
                'constraints': [models.UniqueConstraint(fields=('run', 'model', 'criterion'), name='unique_run_model_criterion')],
            },
        ),
    ]
