# Generated by Django 5.1.15 on 2026-04-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationresult',
            options={'ordering': ['criterion__code'], 'verbose_name': 'Результат расчёта', 'verbose_name_plural': 'Результаты расчётов'},
        ),
    ]
