# Generated by Django 5.1.15 on 2026-03-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MethodologyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('version', models.CharField(max_length=30, unique=True, verbose_name='Версия')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=False, help_text='Только одна методика может быть активной', verbose_name='Активна')),
                ('needs_recalculation', models.BooleanField(default=False, help_text='Устанавливается при изменении весов или формул', verbose_name='Требуется пересчёт')),
            ],
            options={
                'verbose_name': 'Версия методики',
                'verbose_name_plural': 'Версии методики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CriterionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)')),
                ('name_de', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (DE)')),
                ('name_pt', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (PT)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('methodology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='methodology.methodologyversion', verbose_name='Методика')),
            ],
            options={
                'verbose_name': 'Группа критериев',
                'verbose_name_plural': 'Группы критериев',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(help_text='Уникальный код параметра в рамках методики, напр. noise_min', max_length=50, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)')),
                ('name_de', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (DE)')),
                ('name_pt', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (PT)')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Описание (EN)')),
                ('description_de', models.TextField(blank=True, default='', verbose_name='Описание (DE)')),
                ('description_pt', models.TextField(blank=True, default='', verbose_name='Описание (PT)')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='Ед. измерения')),
                ('value_type', models.CharField(choices=[('numeric', 'Числовой'), ('binary', 'Бинарный (да/нет)'), ('categorical', 'Категориальный'), ('custom_scale', 'Индивидуальная шкала'), ('formula', 'Формульная логика'), ('lab', 'Лабораторный'), ('fallback', 'С fallback-логикой')], max_length=30, verbose_name='Тип значения')),
                ('scoring_type', models.CharField(choices=[('min_median_max', 'Min / Median / Max'), ('binary', 'Бинарный (0 или 100)'), ('universal_scale', 'Универсальная шкала (100/70/50/30/0)'), ('custom_scale', 'Индивидуальная шкала (JSON)'), ('formula', 'Формула (JSON)'), ('interval', 'Интервальная шкала')], max_length=30, verbose_name='Тип скоринга')),
                ('weight', models.FloatField(default=0, help_text='Вес параметра в процентах. Сумма весов всех параметров = 100%', verbose_name='Вес (%)')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Min')),
                ('median_value', models.FloatField(blank=True, null=True, verbose_name='Медиана')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Max')),
                ('custom_scale_json', models.JSONField(blank=True, help_text='Формат: {"значение": балл, ...} или [{"from": x, "to": y, "score": z}, ...]', null=True, verbose_name='Индивидуальная шкала (JSON)')),
                ('formula_json', models.JSONField(blank=True, help_text='Описание формулы расчёта для формульных параметров', null=True, verbose_name='Формула (JSON)')),
                ('is_lab', models.BooleanField(default=False, verbose_name='Лабораторный параметр')),
                ('is_required_lab', models.BooleanField(default=False, verbose_name='Обязателен для LAB режима')),
                ('is_required_checklist', models.BooleanField(default=False, verbose_name='Обязателен для CHECKLIST')),
                ('is_required_catalog', models.BooleanField(default=False, verbose_name='Обязателен для CATALOG')),
                ('use_in_lab', models.BooleanField(default=True, verbose_name='Используется в LAB')),
                ('use_in_checklist', models.BooleanField(default=True, verbose_name='Используется в CHECKLIST')),
                ('use_in_catalog', models.BooleanField(default=True, verbose_name='Используется в CATALOG')),
                ('region_scope', models.CharField(choices=[('global', 'Глобальный'), ('ru', 'Только Россия'), ('eu', 'Только Европа')], default='global', max_length=10, verbose_name='Регион')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='methodology.criteriongroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
                'ordering': ['display_order'],
                'constraints': [models.UniqueConstraint(fields=('group', 'code'), name='unique_criterion_code_per_group')],
            },
        ),
    ]
