# Generated by Django 5.1.15 on 2026-03-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0002_criterion_methodology_flatten'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='is_inverted',
            field=models.BooleanField(default=False, help_text='Если включено: min = хорошо (100), max = плохо (0). Для шума, вибрации и т.п.', verbose_name='Инвертированная шкала'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='median_by_capacity',
            field=models.JSONField(blank=True, help_text='Формат: {"2.0": 0.18, "2.5": 0.21, "3.5": 0.30}. Ключ — номинальная мощность кВт, значение — медиана.', null=True, verbose_name='Медианы по мощности (JSON)'),
        ),
    ]
