# Generated by Django 5.1.15 on 2026-03-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0003_add_inverted_and_median_by_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='value_type',
            field=models.CharField(choices=[('numeric', 'Числовой'), ('binary', 'Бинарный (да/нет)'), ('categorical', 'Категориальный'), ('custom_scale', 'Индивидуальная шкала'), ('formula', 'Формульная логика'), ('lab', 'Лабораторный'), ('fallback', 'С fallback-логикой'), ('brand_age', 'Возраст бренда в РФ')], max_length=30, verbose_name='Тип значения'),
        ),
    ]
