# Generated by Django 5.1.15 on 2026-03-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0020_remove_invalid_scale_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['display_order'], 'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='criterion_weight_non_negative'),
        ),
    ]
