# Generated by Django 5.1.15 on 2026-04-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0021_alter_criterion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodologyversion',
            name='tab_description_custom',
            field=models.TextField(blank=True, default='', verbose_name='Описание таба «Пользовательский рейтинг»'),
        ),
        migrations.AddField(
            model_name='methodologyversion',
            name='tab_description_index',
            field=models.TextField(blank=True, default='', verbose_name='Описание таба «По индексу»'),
        ),
        migrations.AddField(
            model_name='methodologyversion',
            name='tab_description_quiet',
            field=models.TextField(blank=True, default='', verbose_name='Описание таба «Самые тихие»'),
        ),
    ]
