# Generated by Django 5.1.15 on 2026-04-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0022_methodologyversion_tab_description_custom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterion',
            name='is_lab',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='show_note_on_site',
        ),
    ]
