# Generated by Django 5.1.15 on 2026-04-14 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0023_remove_is_lab_and_show_note_on_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodologyCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('scoring_type', models.CharField(choices=[('min_median_max', 'Min / Median / Max'), ('binary', 'Бинарный (0 или 100)'), ('universal_scale', 'Универсальная шкала (100/70/50/30/0)'), ('custom_scale', 'Индивидуальная шкала (JSON)'), ('formula', 'Формула (JSON)'), ('interval', 'Интервальная шкала')], max_length=30, verbose_name='Тип скоринга')),
                ('weight', models.FloatField(default=0, help_text='Вес параметра в процентах. Сумма весов всех параметров = 100%', verbose_name='Вес (%)')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Min')),
                ('median_value', models.FloatField(blank=True, null=True, verbose_name='Медиана')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Max')),
                ('is_inverted', models.BooleanField(default=False, help_text='Если включено: min = хорошо (100), max = плохо (0). Для шума, вибрации и т.п.', verbose_name='Инвертированная шкала')),
                ('median_by_capacity', models.JSONField(blank=True, help_text='Формат: {"2.0": 0.18, "2.5": 0.21, "3.5": 0.30}. Ключ — номинальная мощность кВт, значение — медиана.', null=True, verbose_name='Медианы по мощности (JSON)')),
                ('custom_scale_json', models.JSONField(blank=True, help_text='Формат: {"значение": балл, ...} или [{"from": x, "to": y, "score": z}, ...]', null=True, verbose_name='Индивидуальная шкала (JSON)')),
                ('formula_json', models.JSONField(blank=True, help_text='Описание формулы расчёта для формульных параметров', null=True, verbose_name='Формула (JSON)')),
                ('is_required_lab', models.BooleanField(default=False, verbose_name='Обязателен для LAB режима')),
                ('is_required_checklist', models.BooleanField(default=False, verbose_name='Обязателен для CHECKLIST')),
                ('is_required_catalog', models.BooleanField(default=False, verbose_name='Обязателен для CATALOG')),
                ('use_in_lab', models.BooleanField(default=True, verbose_name='Используется в LAB')),
                ('use_in_checklist', models.BooleanField(default=True, verbose_name='Используется в CHECKLIST')),
                ('use_in_catalog', models.BooleanField(default=True, verbose_name='Используется в CATALOG')),
                ('region_scope', models.CharField(choices=[('global', 'Глобальный'), ('ru', 'Только Россия'), ('eu', 'Только Европа')], default='global', max_length=10, verbose_name='Регион')),
                ('note', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodology_entries', to='methodology.criterion', verbose_name='Параметр')),
                ('methodology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodology_criteria', to='methodology.methodologyversion', verbose_name='Методика')),
            ],
            options={
                'verbose_name': 'Параметр методики',
                'verbose_name_plural': 'Параметры методики',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='methodologyversion',
            name='criteria_m2m',
            field=models.ManyToManyField(related_name='methodologies', through='methodology.MethodologyCriterion', to='methodology.criterion', verbose_name='Параметры'),
        ),
        migrations.AddConstraint(
            model_name='methodologycriterion',
            constraint=models.UniqueConstraint(fields=('methodology', 'criterion'), name='unique_methodology_criterion'),
        ),
        migrations.AddConstraint(
            model_name='methodologycriterion',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='mc_weight_non_negative'),
        ),
    ]
