# Generated by Django 5.1.15 on 2026-04-14 11:26

from collections import defaultdict

from django.db import migrations


# Поля, которые копируются из старого Criterion в MethodologyCriterion
MC_FIELDS = [
    "scoring_type", "weight",
    "min_value", "median_value", "max_value",
    "is_inverted", "median_by_capacity",
    "custom_scale_json", "formula_json",
    "is_required_lab", "is_required_checklist", "is_required_catalog",
    "use_in_lab", "use_in_checklist", "use_in_catalog",
    "region_scope", "note", "is_public", "display_order", "is_active",
]


def forwards(apps, schema_editor):
    Criterion = apps.get_model("methodology", "Criterion")
    MethodologyCriterion = apps.get_model("methodology", "MethodologyCriterion")
    ModelRawValue = apps.get_model("catalog", "ModelRawValue")

    # 1. Группируем все Criterion по code
    by_code = defaultdict(list)
    for c in Criterion.objects.all().select_related("methodology").order_by("pk"):
        by_code[c.code].append(c)

    canonical_map = {}  # old_criterion_id -> canonical_criterion_id

    for code, criteria_list in by_code.items():
        # Канонический — из активной методики, если есть; иначе первый
        canonical = None
        for c in criteria_list:
            if c.methodology and c.methodology.is_active:
                canonical = c
                break
        if canonical is None:
            canonical = criteria_list[0]

        for c in criteria_list:
            canonical_map[c.pk] = canonical.pk

            # Создаём MethodologyCriterion для каждой связки methodology+criterion
            mc_kwargs = {
                "methodology_id": c.methodology_id,
                "criterion_id": canonical.pk,
            }
            for field in MC_FIELDS:
                mc_kwargs[field] = getattr(c, field)
            MethodologyCriterion.objects.create(**mc_kwargs)

    # 2. Ремапим ModelRawValue.criterion_id на канонический Criterion
    for old_id, canonical_id in canonical_map.items():
        if old_id != canonical_id:
            ModelRawValue.objects.filter(criterion_id=old_id).update(
                criterion_id=canonical_id
            )

    # 3. Удаляем неканонические Criterion-дубли
    all_canonical_ids = set(canonical_map.values())
    Criterion.objects.exclude(pk__in=all_canonical_ids).delete()


def backwards(apps, schema_editor):
    """Обратная миграция: воссоздаёт дубли Criterion из MethodologyCriterion."""
    Criterion = apps.get_model("methodology", "Criterion")
    MethodologyCriterion = apps.get_model("methodology", "MethodologyCriterion")
    ModelRawValue = apps.get_model("catalog", "ModelRawValue")

    # Идентификационные поля Criterion, которые копируются
    IDENTITY_FIELDS = [
        "code", "name_ru", "name_en", "name_de", "name_pt",
        "description_ru", "description_en", "description_de", "description_pt",
        "unit", "value_type",
    ]

    for mc in MethodologyCriterion.objects.select_related("criterion", "methodology").all():
        canonical = mc.criterion

        # Проверяем, уже ли Criterion привязан к этой методике
        existing = Criterion.objects.filter(
            methodology_id=mc.methodology_id, code=canonical.code
        ).first()
        if existing:
            continue

        # Клонируем Criterion для этой методики
        kwargs = {"methodology_id": mc.methodology_id}
        for field in IDENTITY_FIELDS:
            kwargs[field] = getattr(canonical, field)
        for field in MC_FIELDS:
            kwargs[field] = getattr(mc, field)
        new_criterion = Criterion.objects.create(**kwargs)

        # Ремапим raw values обратно, если эта методика — активная
        if mc.methodology.is_active:
            ModelRawValue.objects.filter(
                criterion_id=canonical.pk
            ).update(criterion_id=new_criterion.pk)

    # Удаляем все MethodologyCriterion
    MethodologyCriterion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0024_create_methodology_criterion"),
        ("catalog", "0010_add_index_verification_lab_status"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
