# Generated by Django 5.1.15 on 2026-04-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0025_populate_methodology_criterion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['code'], 'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.RemoveConstraint(
            model_name='criterion',
            name='unique_criterion_code_per_methodology',
        ),
        migrations.RemoveConstraint(
            model_name='criterion',
            name='criterion_weight_non_negative',
        ),
        migrations.RenameField(
            model_name='methodologyversion',
            old_name='criteria_m2m',
            new_name='criteria',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='custom_scale_json',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='formula_json',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='group',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='is_inverted',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='is_required_catalog',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='is_required_checklist',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='is_required_lab',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='median_by_capacity',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='median_value',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='methodology',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='note',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='region_scope',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='scoring_type',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='use_in_catalog',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='use_in_checklist',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='use_in_lab',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='weight',
        ),
        migrations.AlterField(
            model_name='criterion',
            name='code',
            field=models.CharField(help_text='Уникальный код параметра, напр. noise_min', max_length=50, unique=True, verbose_name='Код'),
        ),
    ]
