# Generated by Django 5.1.15 on 2026-04-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0026_cleanup_criterion_standalone'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='criteria/', verbose_name='Фото'),
        ),
    ]
