# Generated by Django 5.1.15 on 2026-04-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0028_populate_criterion_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methodologycriterion',
            name='note',
        ),
    ]
