# Generated by Django 5.1.15 on 2026-03-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, default='', upload_to='brands/', verbose_name='Логотип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BrandOriginClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('origin_type', models.CharField(choices=[('japanese', 'Японский'), ('chinese_oem', 'Китайский / OEM'), ('european', 'Европейский'), ('other', 'Другой')], max_length=30, verbose_name='Тип происхождения')),
                ('fallback_score', models.FloatField(default=50, help_text='Балл по умолчанию для мощности компрессора при отсутствии данных', verbose_name='Fallback-балл')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origin_class', to='brands.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Происхождение бренда',
                'verbose_name_plural': 'Происхождение брендов',
            },
        ),
    ]
