# Generated by Django 5.1.15 on 2026-03-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandoriginclass',
            name='sales_start_year_ru',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Например: 2015', null=True, verbose_name='Год начала продаж в РФ'),
        ),
    ]
