# Generated by Django 5.1.15 on 2026-03-20 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_restructure_origin_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='origin_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='brands.brandoriginclass', verbose_name='Тип происхождения'),
        ),
        migrations.AlterField(
            model_name='brandoriginclass',
            name='origin_type',
            field=models.CharField(choices=[('japanese', 'Японский'), ('chinese_factory', 'Китайский заводской'), ('chinese_oem', 'Китайский ОЕМ')], max_length=30, unique=True, verbose_name='Тип происхождения'),
        ),
    ]
