# Generated by Django 5.1.15 on 2026-03-18 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=100, verbose_name='Тип сущности')),
                ('entity_id', models.PositiveIntegerField(db_index=True, verbose_name='ID сущности')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('calculate', 'Расчёт')], max_length=20, verbose_name='Действие')),
                ('field_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Поле')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='Новое значение')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Запись аудит-лога',
                'verbose_name_plural': 'Аудит-лог',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_auditl_entity__244637_idx')],
            },
        ),
    ]
