# Generated by Django 5.1.15 on 2026-04-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-slug')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content_ru', models.TextField(help_text='Поддерживает HTML-разметку', verbose_name='Контент (HTML)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
